# Generated by Django 5.1.1 on 2024-10-12 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=350)),
                ('data_nascimento', models.DateField(max_length=8)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('data_ultima_alteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.CharField(max_length=300)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.cliente')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.produto')),
            ],
        ),
    ]
